version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: dms-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: dms
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: dms-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  dms-backend:
    build: .
    container_name: dms-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/dms
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      RABBITMQ_QUEUE: xray-queue
      PORT: 3000
      NODE_ENV: production
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:
  rabbitmq_data:
